Django_auto/urls.py
from django.urls import path
from app01 import views

urlpatterns = [
    path('login/', views.login),
    path('logon/', views.logon),
    path('user/info/', views.user_info),
    path('user/edit/<str:username>/', views.user_edit, name='user_edit'),
    path('user/manager/', views.user_manage),
    path('server/info/', views.service_info),
    path('change/pwd/', views.change_pwd),
    path('show/after/', views.show_after),
    path('logout/', views.logout),
    path('service/user/edit/<str:name>/', views.service_user_edit, name='service_user_edit'),
    path('new/built/user/', views.new_built_user),
    path('monitor/cpu/', views.monitor_cpu),
    path('monitor/mem/', views.monitor_mem),
    path('process/manager/', views.process_manager)
]

app01/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    user_name = models.CharField(max_length=16,verbose_name='用户名')
    user_password = models.CharField(max_length=16,verbose_name='密码')
    user_age = models.IntegerField(verbose_name='年龄')
    gender_choice = (
        (1,'男'),
        (2,'女'),
    )
    user_gender = models.SmallIntegerField(choices=gender_choice,verbose_name='性别')
    depart_choice = (
        (1,'开发部门'),
        (2,'测试部门'),
        (3,'运维部门')
    )
    user_depart = models.SmallIntegerField(choices=depart_choice,verbose_name='部门')
    user_time = models.DateField(max_length=24,verbose_name='入职时间')

app01/views.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.form import LogonModelForm, EditModelForm, LoginModelForm, ChangePasswordForm
from app01.utils.config import SERVER_IP, USERNAME, PASSWORD
import paramiko
from django.views.decorators.csrf import csrf_exempt
import json
from django.utils.safestring import mark_safe

# Create your views here.
# 用户登录
def login(request):
    if request.method == 'GET':
        form = LoginModelForm
        return render(request, 'login.html', {'form': form})

    form = LoginModelForm(data=request.POST)
    if form.is_valid():
        # 验证成功获取的用户名和密码
        username = form.cleaned_data['user_name']
        password = form.cleaned_data['user_password']

        user = models.UserInfo.objects.filter(user_name=username, user_password=password).first()
        if not user:
            form.add_error("user_password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        # 用户名密码正确
        # 将用户名写入session
        request.session["info"] = {'name': user.user_name}
        return redirect('/show/after/')
    return render(request, 'login.html', {'form': form})


# 注册
def logon(request):
    if request.method == 'GET':
        form = LogonModelForm
        return render(request, 'logon.html', {'form': form})
    # 数据校验
    form = LogonModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法保存到数据库
        form.save()
        return redirect('/show/after/')
    return render(request, 'logon.html', {'form': form})


# 当前用户资料
def user_info(request):
    if request.method == 'GET':
        username = request.session.get("info", {}).get("name")
        user_info = models.UserInfo.objects.filter(user_name=username).first()
        return render(request, 'user_info.html', {'info': [user_info]})


# 修改当前用户资料
def user_edit(request, username):
    user_info = models.UserInfo.objects.filter(user_name=username).first()

    if request.method == 'POST':
        form = EditModelForm(request.POST, instance=user_info)
        if form.is_valid():
            form.save()
            return redirect('/show/after/')
    else:
        form = EditModelForm(instance=user_info)

    return render(request, 'user_edit.html', {'form': form})


# 服务器用户管理
def user_manage(request):
    if request.method == 'GET':
        server_ip = SERVER_IP
        username = USERNAME
        password = PASSWORD
        # 创建SSH客户端
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # 连接到服务器
        client.connect(server_ip, username=username, password=password)

        # 执行命令并获取信息
        command = "getent passwd | awk -F: '$3 >= 1000 {print $1}'"
        stdin, stdout, stderr = client.exec_command(command)
        users = stdout.read().decode().strip().split('\n')

        users_groups = []
        for user in users:
            group_command = f"groups {user} | awk -F: '{{print $2}}'"
            group_stdin, group_stdout, group_stderr = client.exec_command(group_command)
            groups = group_stdout.read().decode().strip().split(' ')
            users_groups.append({'user': user, 'groups': groups})
        # 关闭SSH连接
        client.close()
        return render(request, 'user_manage.html', {'users_groups': users_groups})


# 连接服务器获取信息
def service_info(request):
    server_ip = SERVER_IP
    username = USERNAME
    password = PASSWORD
    # 创建SSH客户端
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    # 连接到服务器
    client.connect(server_ip, username=username, password=password)
    # 执行命令并获取信息
    commands = [
        "hostname -I",  # 获取IP地址
        "cat /proc/cpuinfo | grep 'model name' | head -n 1 | awk -F ': ' '{print $2}'",  # 获取CPU信息
        "free -h | awk '/Mem/ {print $2}'",  # 获取内存信息
        "df -h --total | awk '/total/ {print $2}'"  # 获取存储信息
    ]
    server_info = []
    for command in commands:
        stdin, stdout, stderr = client.exec_command(command)
        info = stdout.read().decode().strip()
        server_info.append(info)
    # 关闭SSH连接
    client.close()
    return render(request, 'server_info.html', {'server_info': server_info})


# 用户修改密码
def change_pwd(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            input_name = form.cleaned_data['user_name']
            new_pwd = form.cleaned_data['user_password']

            user = models.UserInfo.objects.filter(user_name=input_name).first()
            if user:
                user.user_password = new_pwd
                user.save()
                return redirect('/login/')
            else:
                context = {
                    'form': form,
                    'error_message': '用户名输入错误',
                }
                return render(request, 'change_pwd.html', context)
    else:
        form = ChangePasswordForm()

    context = {
        'form': form,
    }
    return render(request, 'change_pwd.html', context)

# 登入后界面
def show_after(request):
    if request.method == 'GET':
        # 连接服务器
        server_ip = SERVER_IP
        username = USERNAME
        password = PASSWORD
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(server_ip, username=username, password=password)
        # 获取内存信息
        stdin, stdout, stderr = client.exec_command('free -m')
        output = stdout.read().decode('utf-8')
        # 解析内存信息
        lines = output.strip().split('\n')
        headers = lines[0].split()
        mem = lines[1].split()
        swap = lines[2].split()
        # 已使用内存
        used_mem_head = headers[1]
        used_mem = int(mem[1])
        # 可用内存
        available_mem_head = headers[5]
        available_mem = int(mem[6])
        # 缓存
        buff_mem_head = headers[4]
        buff_mem = int(mem[5])
        # Swap
        swap_total = int(swap[1])
        swap_free = int(swap[3])
        db_data_list = [
            {"value": used_mem, "name": used_mem_head},
            {"value": available_mem, "name": available_mem_head},
            {"value": buff_mem, "name": buff_mem_head},
            {"value": swap_total, "name": "swap_total"},
            {"value": swap_free, "name": "swap_free"},
        ]
        db_data_json = json.dumps(db_data_list)
        # 获取磁盘信息
        stdin, stdout, stderr = client.exec_command('df -m')
        output1 = stdout.read().decode('utf-8')
        # 解析内存信息
        lines1 = output1.strip().split('\n')[1:]
        disk_usage = []
        for line in lines1:
            data = line.split()
            used_percent = data[4].replace('%', '')
            mount_point = data[5]
            disk_usage.append((used_percent, mount_point))
        db_data_list1 = [
            {"value": disk_usage[0][0], "name": disk_usage[0][1]},
            {"value": disk_usage[1][0], "name": disk_usage[1][1]},
            {"value": disk_usage[2][0], "name": disk_usage[2][1]},
            {"value": disk_usage[3][0], "name": disk_usage[3][1]},
            {"value": disk_usage[4][0], "name": disk_usage[4][1]},
            {"value": disk_usage[5][0], "name": disk_usage[5][1]},
            {"value": disk_usage[6][0], "name": disk_usage[6][1]},
        ]
        db_data_json1 = json.dumps(db_data_list1)
        # 获取服务器在线用户
        stdin, stdout, stderr = client.exec_command('who|wc -l')
        output2 = stdout.read().decode('utf-8')
        stdin, stdout, stderr = client.exec_command('ps -ef|wc -l')
        output3 = stdout.read().decode('utf-8')
        # 关闭连接
        client.close()
        return render(request, 'show_after.html',
                      {'db_data_json': db_data_json, 'db_data_json1': db_data_json1, 'online_users': output2,
                       'process': output3})


# 注销
def logout(request):
    request.session.clear()
    return redirect('/login/')


# 服务器用户管理
def service_user_edit(request, name):
    if request.method == 'GET':
        server_ip = SERVER_IP
        username = USERNAME
        password = PASSWORD
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(server_ip, username=username, password=password)

        # 执行命令获取指定用户的组信息
        group_command = f"groups {name} | awk -F: '{{print $2}}'"
        group_stdin, group_stdout, group_stderr = client.exec_command(group_command)
        groups = group_stdout.read().decode().strip().split(' ')
        client.close()

        return render(request, 'service_user_edit.html', {'name': name, 'groups': groups})
    group = request.POST.get('group')
    # 连接服务器
    server_ip = SERVER_IP
    username = USERNAME
    password = PASSWORD
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(server_ip, username=username, password=password)
    # 检查用户输入的所属组在服务器是否存在
    check_group_command = f"getent group {group}"
    check_group_stdin, check_group_stdout, check_group_stderr = client.exec_command(check_group_command)
    check_group_output = check_group_stdout.read().decode().strip()

    if not check_group_output:
        # 返回错误信息给前端，继续渲染编辑页面
        group_command = f"groups {name} | awk -F: '{{print $2}}'"
        group_stdin, group_stdout, group_stderr = client.exec_command(group_command)
        groups = group_stdout.read().decode().strip().split(' ')
        client.close()
        return render(request, 'service_user_edit.html', {'name': name, 'groups': groups, 'message': '所属组不存在'})
    # 执行修改所属组的命令
    group_command = f"sudo usermod -g {group} {name}"
    stdin, stdout, stderr = client.exec_command(group_command)
    group_output = stdout.read().decode()

    client.close()

    return redirect('/user/manager/')  # 重定向到用户列表页面或其他适当的页面


@csrf_exempt
# 服务器用户编辑
def new_built_user(request):
    if request.method == 'GET':
        return render(request, 'new_built_user.html')
    # 获取前端输入的信息

app01/templates/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码界面</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1/css/bootstrap.css">
    <style>
        .login {
            width: 450px;
            height: 300px;
            border: 1px solid #dddddd;
            margin-left: auto;
            margin-right: auto;
            padding: 15px 20px;
            margin-top: 150px;
            /*阴影*/
            box-shadow: 5px 5px 5px #aaa;
        }
        .login h2 {
            text-align: center;
        }
    </style>
</head>
<body>

<div class="login">
    <h2>修改用户密码</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.user_name }}
        </div>
        <div class="form-group">
            <label for="id_user_password">新密码</label>
            {{ form.user_password }}
        </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block">提 交</button>
    </form>
</div>

{% if error_message %}
<script>
    // 如果有错误信息，则触发弹窗事件
    confirm('{{ error_message }}');
</script>
{% endif %}

<script src="/static/js/jquery-3.7.1.min.js"></script>
<script src="/static/plugins/bootstrap-3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录界面</title>
    <link rel="stylesheet" href={% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}>
    <style>
        body {
            background-color: #8ea4f8;
            background-image: url('{% static 'img/bk.jpg' %}');
            background-repeat: no-repeat;
            background-size: cover;

        }

        .login_box {
            width: 400px;
            height: 400px;
            background-color: #fff;
            margin: auto;
            margin-top: 150px;
            border-radius: 5px;
            overflow: hidden;
        }

        .title {
            text-align: center;
            font-size: 28px;
            color: #000;
            margin-top: 80px;
            margin-bottom: 10px;
            letter-spacing: 3px;
            font-family: sans-serif;
        }

        .input_box {
            width: 300px;
            height: 30px;
            padding-left: 10px;
            margin-top: 20px;
            margin-left: 50px;
        }

        .button_box {
            width: 300px;
            height: 35px;
            margin-top: 20px;
            margin-left: 50px;
            border-radius: 5px;
            background-color: #64a9d9;
            cursor: pointer;
            color: #fff;
        }

        .logo_box {
            position: absolute;
            background-color: #fff;
            width: 115px;
            height: 115px;
            border-radius: 100px;
            top: 100px;
            left: 46%;
            text-align: center;
        }

        .logo_img {
            float: left;
            margin-right: 190px;
            height: 120px;
            width: 120px;
        }
    </style>
</head>
<body>
<div class="logo_box"><img class="logo_img" src="{% static 'img/user.png' %}"></div>
<div class="login_box">
    <h1 class="title">欢迎登录</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.user_name }}
            <div style="color: red;padding-left: 60px">{{ form.user_name.errors.0 }}</div>
        </div>
        <div class="form-group">
            {{ form.user_password }}
            <div style="color: red;padding-left: 60px">{{ form.user_password.errors.0 }}</div>
        </div>
        <button type="submit" class="button_box">登录</button>
    </form>
</div>



<script src={% static 'js/jquery-3.7.1.min.js' %}></script>
<script src={% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}></script>
</body>
</html>

app01/templates/logon.html
{% extends 'layout.html' %}
{% block css %}
    .logon {
    width: 900px;
    height: 650px;
    border: 1px solid #dddddd;
    margin-left: auto;
    margin-right: auto;
    padding: 15px 20px;
    margin-top: 50px;
    /*阴影*/
    box-shadow: 5px 5px 5px 5px #aaa;
    }

    .logon h2 {
    text-align: center;
    }
{% endblock %}
{% block content %}
    <div class="logon">
        <h2>注册用户</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-lg btn-block">提 交</button>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            $('#time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });
        })
    </script>
{% endblock %}

app01/templates/manager_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户个人资料编辑</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
</head>
<body>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">编辑个人资料</h3>
        </div>
        <div class="panel-body">
            <form>
                <div class="form-group">
                    xxx
                </div>
                <button type="submit" class="btn btn-primary">保存</button>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

app01/templates/monitor_cpu.html
{% extends 'layout.html' %}
{% block css %}
    .left_bor {
    display: inline-block;
    margin-top: -20px;
    height: 678px;
    width: 300px;
    }

    .left_list {
    font-size: 17px;
    padding-left: 10px;
    padding-top: 10px;
    padding-right: 10px;
    padding-bottom: 10px;
    }
    .hide {
    display: none;
    }
    .frame {
    display: inline-block;
    height: 640px;
    width: 1200px;
    margin-right: 30px;
    margin-top: -10px;
    float: right;
    clear: both;
    }
{% endblock %}
{% block content %}
    <!--左侧列表-->
    <div class="left_bor">
        <div>
            <div>
                <div class="list-group left_list">
                    <a href="#" class="list-group-item active disabled">
                        <span class="glyphicon glyphicon-scale" aria-hidden="true"></span>
                        仪表盘
                    </a>
                    <a href="#" class="list-group-item" onclick="clickme(this)">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        动态监控
                    </a>
                    <div class="hide">
                        <a href="/monitor/cpu/" class="list-group-item" style="background-color: #b9def0">CPU监控</a>
                        <a href="/monitor/mem/" class="list-group-item" style="background-color: #b9def0">内存监控</a>
                    </div>
                    <a href="/process/manager/" class="list-group-item ">
                        <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        进程管理
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--边框-->
    <div class="frame">
        <div class="panel panel-default">
            <div class="panel-heading">CPU动态监控</div>
            <div class="panel-body">
                <iframe src="http://192.168.0.166:3000/d/NgIGV-IIk/cpu-load?orgId=1&refresh=5s&kiosk"
                        style="width:100%;height:560px;padding-top: 1px;padding-left: 1px" frameborder="0" scrolling="No"></iframe>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!--左侧列表点击出现更多选项-->
    <script>
        function clickme(self) {
            let havehide = $(self).next().hasClass("hide")
            if (havehide) {
                $(self).next().removeClass("hide")
            } else {
                $(self).next().addClass("hide")
            }
        }
    </script>
{% endblock %}

app01/templates/monitor_mem.html
{% extends 'layout.html' %}
{% block css %}
    .left_bor {
    display: inline-block;
    margin-top: -20px;
    height: 678px;
    width: 300px;
    }

    .left_list {
    font-size: 17px;
    padding-left: 10px;
    padding-top: 10px;
    padding-right: 10px;
    padding-bottom: 10px;
    }
    .hide {
    display: none;
    }
    .frame {
    display: inline-block;
    height: 640px;
    width: 1200px;
    margin-right: 30px;
    margin-top: -10px;
    float: right;
    clear: both;
    }
{% endblock %}
{% block content %}
    <!--左侧列表-->
    <div class="left_bor">
        <div>
            <div>
                <div class="list-group left_list">
                    <a href="#" class="list-group-item active disabled">
                        <span class="glyphicon glyphicon-scale" aria-hidden="true"></span>
                        仪表盘
                    </a>
                    <a href="#" class="list-group-item" onclick="clickme(this)">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        动态监控
                    </a>
                    <div class="hide">
                        <a href="/monitor/cpu/" class="list-group-item" style="background-color: #b9def0">CPU监控</a>
                        <a href="/monitor/mem/" class="list-group-item" style="background-color: #b9def0">内存监控</a>
                    </div>
                    <a href="/process/manager/" class="list-group-item ">
                        <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        进程管理
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--边框-->
    <div class="frame">
        <div class="panel panel-default">
            <div class="panel-heading">内存动态监控</div>
            <div class="panel-body">
                <iframe src="http://192.168.0.166:3000/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=5s&kiosk"
                        style="width:100%;height:560px;padding-top: 1px;padding-left: 1px" frameborder="0"
                        scrolling="No"></iframe>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <!--左侧列表点击出现更多选项-->
    <script>
        function clickme(self) {
            let havehide = $(self).next().hasClass("hide")
            if (havehide) {
                $(self).next().removeClass("hide")
            } else {
                $(self).next().addClass("hide")
            }
        }
    </script>
{% endblock %}

app01/templates/new_built_user.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="请输入用户名" name="name">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">所属组</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" placeholder="请输入所属组" name="group">
                    <div style="color: red">{{ message }}</div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">用户密码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" placeholder="请输入用户密码" name="password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-info">添 加</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app01/templates/process_manager.html
{% extends 'layout.html' %}
{% block css %}
    .left_bor {
    display: inline-block;
    margin-top: -20px;
    height: 678px;
    width: 300px;
    }

    .left_list {
    font-size: 17px;
    padding-left: 10px;
    padding-top: 10px;
    padding-right: 10px;
    padding-bottom: 10px;
    }
    .hide {
    display: none;
    }
    .frame {
    display: inline-block;
    height: 640px;
    width: 1200px;
    margin-right: 30px;
    margin-top: -10px;
    float: right;
    clear: both;
    }
{% endblock %}
{% block content %}
    <!--左侧列表-->
    <div class="left_bor">
        <div>
            <div>
                <div class="list-group left_list">
                    <a href="#" class="list-group-item active disabled">
                        <span class="glyphicon glyphicon-scale" aria-hidden="true"></span>
                        仪表盘
                    </a>
                    <a href="#" class="list-group-item" onclick="clickme(this)">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        动态监控
                    </a>
                    <div class="hide">
                        <a href="/monitor/cpu/" class="list-group-item" style="background-color: #b9def0">CPU监控</a>
                        <a href="/monitor/mem/" class="list-group-item" style="background-color: #b9def0">内存监控</a>
                    </div>
                    <a href="#" class="list-group-item ">
                        <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
                        进程管理
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--边框-->
    <div class="frame">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="container">
                    <h4 style="width: 100px">进程管理</h4>
                    <div class="col-lg-4" style="float: right;clear: both">
                        <form method="get">
                            <div class="input-group">
                                <input type="text" name="q" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                {#进程表格#}
                <table class="table table-hover table-condensed table-bordered">
                    <thead>
                    <tr>
                        <th>USER</th>
                        <th>PID</th>
                        <th>%CPU</th>
                        <th>%MEM</th>
                        <th>VSZ</th>
                        <th>RSS</th>
                        <th>TTY</th>
                        <th>STAT</th>
                        <th>START</th>
                        <th>TIME</th>
                        <th>COMMAND</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for process in process_info_list %}
                        <tr>
                            {% for info in process %}
                                <td>{{ info }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if filtered_list %}
                    <table class="table table-hover table-condensed table-bordered">
                        <thead>
                        <h4>搜索结果</h4>
                        <tr>
                            <th>USER</th>
                            <th>PID</th>
                            <th>%CPU</th>
                            <th>%MEM</th>
                            <th>VSZ</th>
                            <th>RSS</th>
                            <th>TTY</th>
                            <th>STAT</th>
                            <th>START</th>
                            <th>TIME</th>
                            <th>COMMAND</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in filtered_list %}
                            <tr>
                                {% for search in item %}
                                    <td>{{ search }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
        {#分页#}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}
{% block js %}
    <!--左侧列表点击出现更多选项-->
    <script>
        function clickme(self) {
            let havehide = $(self).next().hasClass("hide")
            if (havehide) {
                $(self).next().removeClass("hide")
            } else {
                $(self).next().addClass("hide")
            }
        }
    </script>

{% endblock %}

app01/templates/user_edit.html
{% extends 'layout.html' %}

{% block css %}
.logon {
    width: 900px;
    height: 500px;
    border: 1px solid #dddddd;
    margin-left: auto;
    margin-right: auto;
    padding: 15px 20px;
    margin-top: 50px;
    /*阴影*/
    box-shadow: 5px 5px 5px 5px #aaa;
}

.logon h2 {
    text-align: center;
}
{% endblock %}

{% block content %}
<div class="logon">
    <h2>修改个人资料</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
    </form>
</div>
{% endblock %}

{% block js %}
<script>
    flatpickr("#id_user_time", {
        dateFormat: "Y-m-d",
        minDate: "today"
    });
</script>
{% endblock %}

app01/templates/user_info.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <span>用户资料</span>
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>用户名</th>
                    <th>年龄</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>入职时间</th>
                </tr>
                </thead>
                <tbody>
                {% for user in info %}
                <tr>
                    <th>{{ user.user_name }}</th>
                    <td>{{ user.user_age }}</td>
                    <td>{{ user.get_user_gender_display }}</td>
                    <td>{{ user.get_user_depart_display }}</td>
                    <td>{{ user.user_time|date:"Y-m-d" }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/edit/{{ user.user_name }}">编辑</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}